### PR TITLE
Handle MARC-8 charset MODCPCT-12

### PR DESCRIPTION
**Pull request by adamdickmeiss**

### CODE REVIEW

**Review by MikeTaylor — COMMENTED** [review]
How does this fix the problem?

**Comment by adamdickmeiss** [comment]
It makes YAZ convert from MARC-8 to UTF-8. The JSON MARC record therefore contains UTF-8 bytes (and not MARC-8).

**Comment by MikeTaylor** [comment]
> It makes YAZ convert from MARC-8 to UTF-8. The JSON MARC record therefore contains UTF-8 bytes (and not MARC-8) which is treated as UTF-8.

Ah, right — `json;charset=marc8` means sort of the opposite of what one might expect, which is "JSON, using the MARC8 charset". Got it.

**Review by MikeTaylor — APPROVED** [review]
LGTM

**Comment by adamdickmeiss** [comment]
> LGTM

I verified with record you showed (OCLC, MARC-8 encoding) I also tested with LoC which returns MARC records in UTF-8.

**Pull request merged**
